backend:
  name: github
  repo: sulenchy/evolym-website

# Publish mode enables editorial workflow for content moderation
publish_mode: editorial_workflow

# Media files will be stored in the repo under public/uploads
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections define the structure for the different content types
collections:
  - name: "products"
    label: "Products"
    folder: "_contents/products"
    i18n: true
    locales: [en, fr, es]
    default_locale: en
    create: true
    extension: "json"
    format: "json-frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "markdown", i18n: true }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Electronics", "Clothing", "Accessories", "Home & Kitchen", "Beauty & Personal Care"], i18n: true }
      - { label: "Tags", name: "tags", widget: "list", i18n: true }
      - { label: "Is New", name: "isNew", widget: "boolean", default: false }
      - { label: "In Stock", name: "inStock", widget: "boolean", default: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
